version: '2'

volumes:
  adaptdata:
    external:
      name: dockeradaptauthoring_adaptdata

services:
  setup:
    #build: .
    image: pvadimr/adaptauttoring:latest
    container_name: adaptauthoring
    # extends:
    #   file: docker-compose.yml
    #   service: authoring
    # volumes_from:
    #   - adaptauthoring
    volumes:
      - adaptdata:/adapt_authoring
    external_links:
      - adaptdb
    command: node install --install Y --serverPort 5000 --serverName localhost --dbHost adaptdb --dbName adapt-tenant-master --dbPort 27017 --dataRoot data --sessionSecret your-session-secret --useffmpeg Y --smtpService dummy --smtpUsername smtpUser --smtpPassword smtpPass --fromAddress you@example.com --name master --displayName Master --email ${ADMIN_EMAIL} --password ${ADMIN_PASSWORD} # && node upgrade --Y/n Y
  upgrade:
    extends:
      service: setup
    command: node upgrade --Y/n Y
